### ISSUE TITLE
List of things people would like to change in the UI after a major update

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3378]
Most likely, we'll have to make some serious changes while preparing the v4.0 update this year.

I'll list all the features people have requested:

* [ ] Add the Send Feedback tab to the quick access panel: #3217
* [ ] Fast transition feature in the filter rules: #3364
* [ ] Search doesn't retain search term #1681
* [ ] Toggle in Log View to show only entries matching filter #1109
* [ ] Configurable Toast/Notification for Automatic Filters Updates #910
* [ ] Add firewall widgets #1129
* [ ] Notify users when they disable Base filter #1617
* [ ] Create a small dragging widget #1231
* [ ] Please divide now Filtering log to HTTP(S) Filtering Log and DNS Requests Log #1706
* [ ] Use swipe gestures to update filters #1237
* [ ] Configurable export/import #1652
* [ ] Add a button to read the current changelog #1487
* [ ] Changes to battery stats screen #1475
* [ ] Add options of "Apps and Statistics" & "Filtering Log" in AdGuard's Notification Bar #2164

**Comment by artemiv4nov** [comment]
Well, almost all issues have been implemented, let's close this task

**Comment by TPS** [comment]
> Well, almost all issues have been implemented, let's close this task

@artemiv4nov I don't understand: _which_ of these are implemented?  All linked issues are closed duplicate to this.  Are you planning to reopen those?
