### ISSUE TITLE
Rework the apps management section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3379]
The apps management section will be seriously reworked in v4.0.

I'll collect all the changes people requested about it in this issue:

Checked checkboxes mean that design is ready for this feature.

* [x] Explain the default exceptions #1737
* [x] Notification on a new app installation #1069
* [x] Issues with apps sharing the same UID #1095
* [x] Separate all apps in 'Apps management' in two groups: system/non-system apps #1110
* [ ] Add ability to set start/end date in Apps Management #972
* [x] Add Allow / Deny / Notify option to firewall / apps management section #1386
* [ ] Cannot do anything with the "Removed apps" entry in the Apps Management settings: #3353 
* [ ] Technical info dialog: package name, uid, so on (check the current version)
* [x] Bulk changes UI bug: #3274
* [x] Notify about disabled function (content blocker): #3202
* [x] Add user/system app filter to Bulk Change in Apps Management: #3033
* [x] Unable to reset settings in firewall section: #3027
* [x] Inconsistent icons in the apps management details section: #3018
* [x] Disabling/enabling https filtering triggers warning alert dialog: #2653 
* [x] Allow user to configure app internet access even when app currently has no internet permission: #2732 - dev
* [x] Change the way batch actions in Apps Management work for the default exclusions: #2648
* [x] An easy way to recognize whether https filtering is enabled?: #2648 - dublicate
* [x] Show Log Data of an App in 'Apps Management': #2412
* [x] Show a toast notification if network access is restricted for an app: #2192 - dev
* [x] About the warning of "In order to enable HTTPS filtering for this app, you should turn it on system wide.": #2185 - dev
* [x] Auto select contextual app in apps management: #1423
* [x] Apps mgtm should save the "date range" value (today/last 30 days/etc) #1654 - dev
* [x] [Feature request] Highlight newly installed apps in firewall list #478
* [x] GCM notifications and Firewall rules: #347 - dev
* [x] Add abroad (roaming) mode: #108
* [x] Allow AdGuard firewall to block app traffic in roaming connections #3144
* [x] Remember search/filter selection and scroll location #1387 - dev
* [x] Rework Firewall functions for Adguard #1306
* [x] Feature Request: cosmetical changes Firewall #2117
* [x] When holding down an app's bar in AdGuard's "Apps and Statistics", open that app's App info in Android settings. #2165
* [x] Show the list of top domains used by the app in App details screen #111
* [ ] Add a "Data Bank" feature to AdGuard firewall #3215
* [ ] Firewall profiles #1239 
* [ ] [Request] Network Profiles, like which AdGuard options would be enabled/disabled for each WiFi network or mobile data #1931 - dublicate #1239
* [ ] Add an option to packet-block multiple apps #2996  - dublicate #2493
* [ ] Multi-select apps and change their settings: #2493

**Comment by TPS** [comment]
@artemiv4nov Are you planning to reopen the linked issues that are _not_ implemented?

**Comment by ameshkov** [comment]
We'll audit the tasks on v4.0 closer to the release date and see which ones should be shifted to a later date.
