### ISSUE TITLE
Disabling Tracking protection does not disable the corresponding filter lists

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#4599]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 nightly

### Environment

```markdown
- OS: Android
- Device: Xiaomi
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Disable "Tracking protection"
2. Visit any website or app, for instance "learnadguard.pages.dev/metrika"
3. Check the filtering log

Second thing: 
1. Go to Settings -> Filtering -> Filters -> Privacy filters
2. Privacy filters group is still enabled

### Expected Behavior

1. `mc.yandex.ru` is NOT blocked
2. Privacy filters group is marked as "inactive because Tracking protection is disabled"

### Actual Behavior

1. `mc.yandex.ru` is still blocked
2. Privacy filters group is still enabled
