### ISSUE TITLE
"Block trackers" and "Remove tracking parameters from URLs" are not enabled in the Standard and High tracking protection levels

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#4631]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 Nightly 96

### Environment

```markdown
- OS: Android 12
- Device: Xiaomi
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Open Tracking protection
2. Enable the "Standard level"
3. Switch to "Custom"
4. Check if "Block trackers" is enabled.

Repeat the same, but now with "High" or "Ultimate" levels and check the "Remove parameters" feature status.

### Expected Behavior

"Block trackers" and "Remove parameters" should be enabled.

### Actual Behavior

They're never enabled.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by loca-lhost** [comment]
Turning these settings to standard, high or ultimate on turns off privacy filters. Is these an intended behaviour? It doesn't do that on v3
