### ISSUE TITLE
Wrong underlying settings for the Tracking protection levels

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#4632]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 Nightly 96

### Environment

```markdown
- OS: Android 12
- Device: Xiaomi
```

### Root access

- [X] Yes, I have it.

### Issue Details

The algorithm is the following:

1. Switch Tracking protection to one of the available levels: Standard, High, Ultimate
2. Then switch it to "Custom" and check what settings were enabled

### Expected Behavior

Here's what we should have there.

### Standard

* [x] "Block trackers"
* [x] "Ask websites not to track you"
* [x] "Remove X-Client-Data header" 

### High

* [x] "Block trackers"
* [x] "Remove tracking parameters from URLs"
* [x] "Hide your search queries"
* [x] "Ask websites not to track you"

* [x] "Self-destruct third-party cookies"

* [x] "Remove X-Client-Data header" 

### Ultimate

* [x] "Block trackers"
* [x] "Remove tracking parameters from URLs"
* [x] "Hide your search queries"
* [x] "Ask websites not to track you"

* [x] "Self-destruct third-party cookies"
* [x] "Block WebRTC"
* [x] "Block Push API"
* [x] "Block Location API"
* [x] "Hide Referer from third parties
* [x] "Hide your User-Agent"
* [x] "Remove X-Client-Data header" 

### Actual Behavior

The current settings are different.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
