### ISSUE TITLE
Wrong tracking protection options shown in activity log

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#5073]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3

### Environment

```markdown
- OS: android 13
- Device: galaxy s23 ultra
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Go to activity log
2. Click on any url with grey shown
3. Look in tracking protection

### Expected Behavior

Current tracking protection options shown

### Actual Behavior

Wrong tracking protection options shown

### Screenshots

![Screenshot_20231110_171717_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/118186787/ec9c7dfb-51a8-4ffe-a8ae-54d365e7f88e)
![Screenshot_20231110_172154_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/118186787/8892702b-62b5-41b9-ae7c-c89dd8389e2d)

### Additional Information

It shows first party cookies are being destructed when i dont have that option enabled.

**Comment by maxikuzmin** [comment]
@jordanswrld94 thanks! I tested this and was able to reproduce the problem. We'll be fixing it in the next updates

**Comment by jordansworld** [comment]
@maxikuzmin this issue still exists
