### ISSUE TITLE
Gray out the toggle switches on the tracking protection screen when the main tracking protection switch is disabled

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#5395]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5

### Environment

- OS version: Android 12 (MIUI 13)

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

Automatic DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Open AG & navigate to the second tab (Protection)
2. Tap on the second item (Tracking Protection).
3. If the main switch for Tracking Protection is enabled, then disable it. If already disabled, then see next step.
4. Scroll down on the same page and you will see that the user is still able to toggle the custom settings (switches) (enable/disable) under General settings, Tracking methods, Browser API, Miscellaneous.

### Expected Behavior

After performing Step 3 mentioned above, when the user scrolls down to see all the other options on that page, the toggle switch state should be "**Switch OFF - Disabled**" for all the settings on that page as seen in the screenshot. Currently, it allows the user to toggle the switches although it may not actually applying those settings. This is not a good design from a UI perspective.

### Actual Behavior

After performing Step 3 mentioned above, when the user scrolls down to see the other options on that page, it allows the user to toggle the switches.

### Screenshots

![image](https://github.com/user-attachments/assets/6d147baf-c311-4947-8da2-b3b256d117ff)

### Additional Information

This should not just be applicable for this particular page, but the same logic should apply throughout the app.
Another page where this needs to be implemented:

Second tab > DNS Protection > DNS filters > Turn off the main switch on the top for "DNS filters"
You will see that the options below still allow the user to toggle the other settings "User rules", etc. The switches should be in the "Switch OFF - Disabled" state.

**Comment by Versty** [comment]
@Nzzyme Hi! 

We are currently improving the screens of our application step by step. We have plans on implementing the logic described above on Tracking protection screen as well. Thank you for bringing this to our attention!

**Comment by Nzzyme** [comment]
The updated title of this issue is not technically right. When the main tracking protection switch is off, then all the switches under that page should be in "Switch OFF and disabled" state (see above screenshot) and not just grayed out.

Let's say that one switch on that page was switched on, then when the main switch is turned off, then if it is just grayed out, then it will technically be "Switch ON - Disabled" which means that the setting is ON in the background but just does not allow the user to change it.

**Comment by Versty** [comment]
@Nzzyme We have additionally discussed this issue, disabling elements completely is not in accordance with our current design guidelines. Therefore, we have implemented a gray out approach to display the inactive state of elements on the tracking protection screen.

**Comment by Nzzyme** [comment]
> @Nzzyme We have additionally discussed this issue, disabling elements completely is not in accordance with our current design guidelines. Therefore, we have implemented a gray out approach to display the inactive state of elements on the tracking protection screen.

Will that be rolled out in the next version or is it already available? I just checked by toggling "Tracking protection" to off and still see that all the other options below on that page allow me to toggle them on or off instead of the switches being grayed out.
